# resources:
#   repositories:
#   - repository: react-ui-monolith
#     type: git
#     name: Narottam-project
#     ref: refs/heads/main

trigger: none

pool: Hosted
 
stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - template: node-build.yml
